/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/threeJS/model.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/model.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="floor1"
          geometry={nodes.floor1.geometry}
          material={materials.gray}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="canvas"
          geometry={nodes.canvas.geometry}
          material={materials.white}
          position={[-10.6, -1.3, -6.73]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="book1"
          geometry={nodes.book1.geometry}
          material={materials.white}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="book2"
          geometry={nodes.book2.geometry}
          material={materials.black1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="tvHub"
          geometry={nodes.tvHub.geometry}
          material={materials.white}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group
          name="laptop"
          position={[0, 0, 0.02]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="kaedim_mesh_156_Mesh002"
            geometry={nodes.kaedim_mesh_156_Mesh002.geometry}
            material={materials.black1}
          />
          <mesh
            name="kaedim_mesh_156_Mesh002_1"
            geometry={nodes.kaedim_mesh_156_Mesh002_1.geometry}
            material={materials.silver1}
          />
          <mesh
            name="kaedim_mesh_156_Mesh002_2"
            geometry={nodes.kaedim_mesh_156_Mesh002_2.geometry}
            material={materials.silver2}
          />
          <mesh
            name="kaedim_mesh_156_Mesh002_3"
            geometry={nodes.kaedim_mesh_156_Mesh002_3.geometry}
            material={materials.white}
          />
        </group>
        <mesh
          name="easel"
          geometry={nodes.easel.geometry}
          material={materials.black1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="tvController"
          geometry={nodes.tvController.geometry}
          material={materials.black1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="tv"
          geometry={nodes.tv.geometry}
          material={materials.black1}
          position={[12.16, 2.81, 0.57]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="board"
          geometry={nodes.board.geometry}
          material={materials.white}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="tvShelf"
          geometry={nodes.tvShelf.geometry}
          material={materials.orange}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="wall2"
          geometry={nodes.wall2.geometry}
          material={materials.white}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group name="wall1" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_2_Mesh002"
            geometry={nodes.kaedim_mesh_2_Mesh002.geometry}
            material={materials.gray}
          />
          <mesh
            name="kaedim_mesh_2_Mesh002_1"
            geometry={nodes.kaedim_mesh_2_Mesh002_1.geometry}
            material={materials.white}
          />
        </group>
        <group name="chair3" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_31_Mesh002"
            geometry={nodes.kaedim_mesh_31_Mesh002.geometry}
            material={materials.white}
          />
          <mesh
            name="kaedim_mesh_31_Mesh002_1"
            geometry={nodes.kaedim_mesh_31_Mesh002_1.geometry}
            material={materials.brown}
          />
        </group>
        <group name="chair4" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_36_Mesh002"
            geometry={nodes.kaedim_mesh_36_Mesh002.geometry}
            material={materials.white}
          />
          <mesh
            name="kaedim_mesh_36_Mesh002_1"
            geometry={nodes.kaedim_mesh_36_Mesh002_1.geometry}
            material={materials.brown}
          />
        </group>
        <group name="chair6" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_45_Mesh002"
            geometry={nodes.kaedim_mesh_45_Mesh002.geometry}
            material={materials.white}
          />
          <mesh
            name="kaedim_mesh_45_Mesh002_1"
            geometry={nodes.kaedim_mesh_45_Mesh002_1.geometry}
            material={materials.brown}
          />
        </group>
        <mesh
          name="floor2"
          geometry={nodes.floor2.geometry}
          material={materials.orange}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group name="chair5" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_50_Mesh002"
            geometry={nodes.kaedim_mesh_50_Mesh002.geometry}
            material={materials.white}
          />
          <mesh
            name="kaedim_mesh_50_Mesh002_1"
            geometry={nodes.kaedim_mesh_50_Mesh002_1.geometry}
            material={materials.brown}
          />
        </group>
        <mesh
          name="table"
          geometry={nodes.table.geometry}
          material={materials.brown}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group name="chair1" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_6_Mesh002"
            geometry={nodes.kaedim_mesh_6_Mesh002.geometry}
            material={materials.white}
          />
          <mesh
            name="kaedim_mesh_6_Mesh002_1"
            geometry={nodes.kaedim_mesh_6_Mesh002_1.geometry}
            material={materials.brown}
          />
        </group>
        <group name="chair2" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_8_Mesh002"
            geometry={nodes.kaedim_mesh_8_Mesh002.geometry}
            material={materials.white}
          />
          <mesh
            name="kaedim_mesh_8_Mesh002_1"
            geometry={nodes.kaedim_mesh_8_Mesh002_1.geometry}
            material={materials.brown}
          />
        </group>
        <group name="chair7" rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            name="kaedim_mesh_9_Mesh002"
            geometry={nodes.kaedim_mesh_9_Mesh002.geometry}
            material={materials.white}
          />
          <mesh
            name="kaedim_mesh_9_Mesh002_1"
            geometry={nodes.kaedim_mesh_9_Mesh002_1.geometry}
            material={materials.brown}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model.glb");
